# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypr_ng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='edited_by',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[(b'new', b'new'), (b'sent_to_external_editor', b'sent_to_external_editor'), (b'processing', b'processing'), (b'published', b'published'), (b'pending', b'pending'), (b'rejected', b'rejected')], max_length=50),
        ),
    ]
